locations:
  reads-dir: tests/sample_data/reads/
  output-dir: output/
  genome-fasta: tests/sample_data/sample.fasta
  cdna-fasta: tests/sample_data/sample.cdna.fasta
  gtf-file: tests/sample_data/sample.gtf

organism: '' # mmusculus, hsapiens, btaurus...

mapping:
  mapper: 'hisat2' # options are star or hisat2
  genome_build: 'GRCm38'  #genome build version identifier that is used in hisat2 index file names

DEanalyses:
  #names of analyses can be anything but they have to be unique for each combination of case control group comparisons.
  analysis1:
    #if multiple sample names is provided, they must be separated by comma
    case_sample_groups: "HBR"
    control_sample_groups: "UHR"
    covariates: ''


execution:
  jobs: 16
  nice: 19
  rules:
    __default__:
      threads: 1
      memory: 2048
    translate_sample_sheet_for_report:
      threads: 1
      memory: 1024
    trim_qc_reads:
      threads: 1
      memory: 4096
    star_index:
      threads: 16
      memory: 32768
    hisat2-build:
      threads: 16
      memory: 32768
    salmon_index:
      threads: 8
      memory: 4096
    salmon_quant:
      threads: 8
      memory: 4096
    counts_from_salmon:
      threads: 1
      memory: 1024
    collate_read_counts:
      threads: 1
      memory: 1024
    norm_counts_deseq:
      threads: 1
      memory: 1024
    star_map:
      threads: 8
      memory: 16384
    hisat2:
      threads: 8
      memory: 16384
    index_bam:
      threads: 1
      memory: 1024
    multiqc:
      threads: 2
      memory: 1024
    coverage_bamCoverage:
      threads: 1
      memory: 4096
    coverage_megadepth:
      threads: 1
      memory: 4096
    count_reads:
      threads: 1
      memory: 4096
    featureCounts:
      threads: 4
      memory: 4096
    check_annotation_files:
      threads: 1
      memory: 16384
    reports:
      threads: 1
      memory: 4096

counting:
  counting_mode: "Union" # other options are "IntersectionStrict" and "IntersectionNotEmpty"
  drop_nonunique: TRUE # boolean, When set to TRUE, multi-mapping reads are not counted (see inter.feature argument of summarizeOverlaps)
  strandedness: "0" # other options are "0(unspecific)" or "1(forward)" and "2(reverse)" for strand-specific read-counting
  feature: "exon"
  annotation_file_type: "GTF"
  group_feature_by: "gene_id"
  yield_size: 2000000 # how many reads to process at a time (this impacts memory consumption)


tools:
  gunzip:
    executable: "gunzip"
    args: ""
  multiqc:
    executable: "multiqc"
    args: ""
  star_map:
    executable: "STAR"
    args: ""
  star_index:
    executable: "STAR"
    args: ""
    # If STAR gives an error then that error message is likely suggest the parameter to adjust.
    # args: "--limitGenomeGenerateRAM 31000000000"
  hisat2:
    executable: "hisat2"
    args: ""
    # If low alignment rates are observed with "--fast" setting,
    # other options to try are "--sensitive or --very-sensitive".
  hisat2-build:
    executable: "hisat2-build"
    args: ""
  samtools:
    executable: "samtools"
    args: ""
  salmon_index:
    executable: "salmon"
    args: "index"
  salmon_quant:
    executable: "salmon"
    args: "quant"
  Rscript:
    executable: "Rscript"
    args: "--vanilla"
  sed:
    executable: "sed"
    args: ""
  fastp:
    executable: "fastp"
    args: "--adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
    # Please refer to fastp manual about setting adapter sequences: https://github.com/OpenGene/fastp#adapters
  bamCoverage:
    executable: "bamCoverage"
    args: "--normalizeUsing BPM --numberOfProcessors 2"
    # see https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html
    # for more detailed arguments used for normalising coverage data files
  megadepth:
    executable: "megadepth"
    args: ""
  featureCounts:
    executable: "featureCounts"
    args: ""

